# Generated by Django 3.1.5 on 2021-01-15 11:08

import QRCode.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=128)),
                ('taux', models.PositiveIntegerField(validators=[QRCode.models.validate_taux])),
            ],
            options={
                'ordering': ['nom', 'taux'],
            },
        ),
    ]
